//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsman.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurment
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public decimal Height { get; set; }
        public decimal ChestSize { get; set; }
        public decimal WaistSize { get; set; }
        public decimal HipSize { get; set; }
        public int FootSize { get; set; }
        public decimal HeadSize { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
